# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install apps
        run: |
          sudo apt-get install libmpc-dev libgmp-dev libmpfr-dev
          sudo apt-get install flex bison
          sudo apt-get install libsdl-dev
          sudo apt-get install nasm
      - name: Git clone
        run: |
          mkdir ~/src                 # Source code
          mkdir ~/i686-pc-elf-build   # Temporary build files
          mkdir ~/i686-pc-elf         # Toolchain install destination
          git clone git://sourceware.org/git/binutils.git ~/src/binutils
          git clone git://gcc.gnu.org/git/gcc.git ~/src/gcc
          git clone git://git.qemu-project.org/qemu.git ~/src/qemu
          git clone git://sourceware.org/git/gdb.git ~/src/gdb
          cd ~/src/binutils ; git checkout binutils-2_23_1
          cd ~/src/gcc ; git checkout gcc-4_8-branch
          cd ~/src/qemu ; git checkout v1.5.0
          cd ~/src/gdb ; git checkout gdb_7_6-branch
      - name: Make
        run: |
          mkdir ~/i686-pc-elf-build/binutils ; cd ~/i686-pc-elf-build/binutils
          ~/src/binutils/configure --prefix=$HOME/i686-pc-elf --target=i686-pc-elf --disable-shared --disable-nls
          make -j 4  # parallel make for 4 cpus
          make install
          mkdir ~/i686-pc-elf-build/gcc ; cd ~/i686-pc-elf-build/gcc
          ~/src/gcc/configure --prefix=$HOME/i686-pc-elf --target=i686-pc-elf --enable-languages=c --disable-shared --disable-nls
          make -j 4 all-gcc
          make install-gcc
          mkdir ~/i686-pc-elf-build/qemu ; cd ~/i686-pc-elf-build/qemu
          ~/src/qemu/configure --prefix=$HOME/i686-pc-elf --target-list=i386-softmmu --enable-sdl
          make -j 4
          make install
          mkdir ~/i686-pc-elf-build/gdb ; cd ~/i686-pc-elf-build/gdb
          ~/src/gdb/configure --prefix=$HOME/i686-pc-elf --target=i686-pc-elf
          make -j 4
          make install
          export PATH=$HOME/i686-pc-elf/bin:$PATH









